# Generated by Django 5.2.4 on 2025-08-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0005_cart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order',
        ),
    ]
